import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import MainNavbar from "@/_mycomponents/navigation/MainNavbar";
import Footer from "@/components/layout/Footer";
import ReduxStoreProvider from "@/_mycomponents/providers/ReduxStoreProvider";
import SessionProvider from "@/_mycomponents/providers/SessionProvider"; // Import the new provider

const jakarta = Plus_Jakarta_Sans({ 
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Music Funeral",
  description: "Generated by create next app",
};

// -- props -- //
type Props = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={jakarta.className + " dark:bg-[#111423] min-h-screen flex flex-col"}>
        <ReduxStoreProvider>
          <SessionProvider> {/* Wrap the app with SessionProvider */}
            <MainNavbar />
            <main className="flex-grow">{children}</main>
            <Footer />
          </SessionProvider>
        </ReduxStoreProvider>
      </body>
    </html>
  );
}
